site_name: python-by-examples
site_url: https://python-by-examples.readthedocs.io
repo_url: https://github.com/devops-by-examples/Python
strict: true
theme:
  name: material
  palette:
    primary: indigo
  font:
    text: 'Roboto'
  logo: 'assets/images/logo.png'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - About: index.md
  - Overview: index.md
  - Variables:
    - Introduction: variables/introduction.md
  - Data Types:
    - Introduction: datatypes/introduction.md
    - Strings: datatypes/strings.md
  - Loops: 
    - Introduction: loops/introduction.md
    - While: loops/while.md
    - For: loops/for.md
    - Problems: loops/problems.md